opt_in_rules:
  - anyobject_protocol
  - array_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - modifier_order
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - unavailable_function
line_length:
  ignores_comments: false
  ignores_function_declarations: false
  ignores_interpolated_strings: false
  warning: 100
trailing_comma:
  mandatory_comma: true
