language: swift
os: osx
osx_image: xcode11.3
before_install:
  - brew update
  - brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/e49548cbdf6aed9ec715613ba38fcdd389abd9fc/Formula/shellcheck.rb
  - brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/850ae1b380fd27dc034aff30e228cea50913cdff/Formula/shfmt.rb
  - brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/41ed92812a0df927c6cd2b4b5f438e56574726e5/Formula/swiftlint.rb
  - brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/c5a2985ae03734adfc0c4d23c15cf6deb9bf648e/Formula/swiftformat.rb
script:
  - ./script/lint
  - make
before_deploy:
  - git config --local user.name "Michael Sanders"
  - git config --local user.email "michael.sanders@fastmail.com"
  - ./script/archive --package
deploy:
  provider: releases
  api_key:
    secure: HSQTDi4+GFGvvqKKKapUBlUdt5Gqkbz1G7Eo9f2axWQZsjqRUgvFgOUbEApw4JDsw4yscjNQAOFeirOLnzqp3eHmTV4L+s0rJEvN4kyekE7iXiIjGFH1Qh972kNGyx25xwuWB89ixpKHU+zdMUqEg9x7WwDoZxhyLXu0Ubzv9kzR+Jp0TRIBNNVn6F3KYnqk64FvMVgU4WZR+FWQsC2vJZ6jT/C91y0/DuopIgCqnbzwkl9rZBAwnlbgCslBuNLeOCN0yG6PmITQ2CnrSB89AG038RjoIUwlovDTIH/HzUFEJ/VaEN+LVcCo+ccRQ3kR61PIQnOWe6OtQspRdgsTtPAW7byuX/Y9cjoTNqXoQtjgV64pWRf6rQ+7mZoCKDMt6d1eyJasmAxWGVA6hmcsVU9HeuI32fsYVDshOG99VbOKpK5C/AEoA6jgFL0HEmZzz3BEkZHV451xIybCMbVeWqLwu5o3jI+dd9SYHgmCaCwEESSjeC3PChe6Of/MdeJxLiX4oz4HqFiZHQP9zzeKH8RDTOpGkHQM1EKatOor5hkrhVh/1ZBi4QudUPTrQFwBnjK1MuSmSMRDItFivpNertpQVsmHKLasl2k1KEnlwasffHA2ysMsLrcT+bnLyGSbcK6x6CEALr7Llo5IKhnebPHeaEvBKTQKyPQeqFVbMG0=
  file: ./archive/zero-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    master: true
    repo: zero-sh/zero.sh
    tags: true
