addons:
  homebrew:
    update: true
language: swift
os: osx
osx_image: xcode11.3
before_install:
  - cd "$(mktemp -d)"
  - echo "859c18f80d547d0911fafe1a83696a19dfc6bfdeea69129c0097fd34cfe56ceb  ./shellcheck.rb" >> formulas.sha256sum
  - echo "4b86dcee11a3cc9ef13a6b8b491deedf0b88d1b3d929b4e2107076711f1c93e8  ./shfmt.rb" >> formulas.sha256sum
  - echo "4f3f6a6315325633be0416d5f246d4a285130830c1d6d43db07fff8e22408534  ./swiftlint.rb" >> formulas.sha256sum
  - echo "7fca2e48f852c4438c6fbce475cd6448c506725bdea4e9a9ceb894cb7d9e6f62  ./swiftformat.rb" >> formulas.sha256sum
  - curl --proto "=https" --tlsv1.2 -sSf https://raw.githubusercontent.com/Homebrew/homebrew-core/d4069ff274c2c45d20edf45c10ee0a91f99829f1/Formula/shellcheck.rb -o shellcheck.rb
  - curl --proto "=https" --tlsv1.2 -sSf https://raw.githubusercontent.com/Homebrew/homebrew-core/25c680332e18dd2e0dfb959441801241f54b1135/Formula/shfmt.rb -o shfmt.rb
  - curl --proto "=https" --tlsv1.2 -sSf https://raw.githubusercontent.com/Homebrew/homebrew-core/55becd959f7ab1fd412ac26c36795fcc235ad741/Formula/swiftlint.rb -o swiftlint.rb
  - curl --proto "=https" --tlsv1.2 -sSf https://raw.githubusercontent.com/Homebrew/homebrew-core/b7a4a2fc5a490bd10a4eccbb1b0c53693ff2d9a6/Formula/swiftformat.rb -o swiftformat.rb
  - shasum --algorithm 256 --check formulas.sha256sum
  - brew reinstall --force-bottle ./shellcheck.rb
  - brew reinstall --force-bottle ./shfmt.rb
  - brew reinstall --force-bottle ./swiftlint.rb
  - brew reinstall --force-bottle ./swiftformat.rb
  - cd -
script:
  - ./script/lint
  - make
before_deploy:
  - git config --local user.name "Michael Sanders"
  - git config --local user.email "michael.sanders@fastmail.com"
  - ./script/archive --package
deploy:
  provider: releases
  api_key:
    secure: HSQTDi4+GFGvvqKKKapUBlUdt5Gqkbz1G7Eo9f2axWQZsjqRUgvFgOUbEApw4JDsw4yscjNQAOFeirOLnzqp3eHmTV4L+s0rJEvN4kyekE7iXiIjGFH1Qh972kNGyx25xwuWB89ixpKHU+zdMUqEg9x7WwDoZxhyLXu0Ubzv9kzR+Jp0TRIBNNVn6F3KYnqk64FvMVgU4WZR+FWQsC2vJZ6jT/C91y0/DuopIgCqnbzwkl9rZBAwnlbgCslBuNLeOCN0yG6PmITQ2CnrSB89AG038RjoIUwlovDTIH/HzUFEJ/VaEN+LVcCo+ccRQ3kR61PIQnOWe6OtQspRdgsTtPAW7byuX/Y9cjoTNqXoQtjgV64pWRf6rQ+7mZoCKDMt6d1eyJasmAxWGVA6hmcsVU9HeuI32fsYVDshOG99VbOKpK5C/AEoA6jgFL0HEmZzz3BEkZHV451xIybCMbVeWqLwu5o3jI+dd9SYHgmCaCwEESSjeC3PChe6Of/MdeJxLiX4oz4HqFiZHQP9zzeKH8RDTOpGkHQM1EKatOor5hkrhVh/1ZBi4QudUPTrQFwBnjK1MuSmSMRDItFivpNertpQVsmHKLasl2k1KEnlwasffHA2ysMsLrcT+bnLyGSbcK6x6CEALr7Llo5IKhnebPHeaEvBKTQKyPQeqFVbMG0=
  file: ./archive/zero-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    master: true
    repo: zero-sh/zero.sh
    tags: true
